### PR TITLE
Df branch3 - #7 Delete a Post 

### PR DESCRIPTION
**Pull request by DeVanteFarmer**
#7 Delete a Post - https://trello.com/c/YGOiZglv
**Description**
This PR introduces a new feature that allows authors to delete posts they have written. The feature includes a delete confirmation process to ensure that posts are only removed when explicitly confirmed by the author. The process follows these steps:

When an author views a post they have written, they are given the option to delete it.
Upon selecting the delete option, the author is presented with a confirmation prompt.
If the author confirms the deletion, the post is removed from the system, and the author is redirected to their list of posts.
If the author cancels the deletion, the post remains intact, and the author is redirected back to the post details.

**Fixes**: None (No specific issue number associated with this PR)

**Type of Change**
New feature (non-breaking change which adds functionality)

**Motivation and Context**
This feature is essential for content management within the application, providing authors with control over their published content. By enabling authors to delete their own posts, we ensure that they can manage their content as they see fit, removing posts that are no longer relevant or desired.

**Dependencies**
No new dependencies are introduced with this change.

**Testing Instructions**
1. Set Up Your Environment:
- Ensure your current work is committed: git add . and git commit -m "Your message"
- Switch to the main branch: git checkout main
- Fetch the latest changes: git fetch --all
- Checkout the feature branch: git checkout df-branch3
- If necessary, pull the latest changes on the branch: git pull origin df-branch3

2. Database Setup:
- If you haven't created the Tabloid MVC database, please do so using the provided SQL scripts.
- Run the SQL script to seed the database with initial data: SQL Seed Data

3. Run the Application:
- Launch the application by pressing F5 or Ctrl + F5 in Visual Studio.

4. Test the Delete Functionality:
- Log in as an author. (admin@example.com)
- Navigate to Post page by clicking the "Posts" link in the navbar. 
_To protect the current database_
- Add a new post
Title: "Testing Post Deletion"
Content: "Testing Content"
_After creating the new post_
- Click the "Delete" button on the post that you created "Testing Post Deletion".
- Confirm the deletion when prompted.
- Verify that the post is no longer listed in "My Posts" page by clicking the "My Posts" link in the navbar. Also, ensure it is removed from the database. 
- 
5. Test the Cancel Functionality:
- Navigating to the delete confirmation page of another post.
- Select the "Cancel" option.
- Verify that you are redirected back to the posts page and that the post has not been deleted.

**Checklist**

- [x]  My code follows the style guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly in hard-to-understand areas.
- [x]  My changes generate no new warnings or errors.
- [x]  I have added test instructions that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
One small change - have them create a new post then delete the post they created:

Add a new post - 
Title: Testing
Content: Testing Content


Then have them delete the post they created to protect the data!

**Comment by DeVanteFarmer** [comment]
Changes made.

**Comment by wicamo96** [comment]
Looks good! Potential conflict with comments once thats merged.

**Comment by dmaceylewis** [comment]
Works well!!

**Pull request merged**
