### PR TITLE
Df Branch2 - #4 View Current User's Posts

### PR DESCRIPTION
**Pull request by DeVanteFarmer**
**Description**
#4 View Current User's Posts - https://trello.com/c/Nd10bHSS
This PR includes the implementation of a feature that allows authors to view a list of all the posts they have written. The posts are displayed on the "My Posts" page, which is accessible via the "My Posts" link in the navigation menu. Each post in the list shows the title, author, and category, and the posts are ordered by creation date with the most recent posts appearing at the top.

**Fixes**: # (issue) - None

**Type of Change**

New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)

**Motivation and Context**
The motivation for this change is to provide authors with the ability to easily manage their own posts. This includes viewing their content directly from the "My Posts" page. 

**Dependencies**
No new dependencies are required for this change.

Testing Instructions

1.Set Up Your Environment:

- Ensure your current work is committed: git add . and git commit -m "Your message"
- Switch to the main branch: git checkout main
- Fetch the latest changes: git fetch --all
- Checkout my branch: git checkout df-branch2
- If necessary, pull the latest changes on the branch: git pull origin df-branch2

2.Database Setup:

- If you haven't created the Tabloid MVC database, please do so using the provided SQL scripts.
- Run the SQL script to seed the database with initial data: SQL Seed Data

3.Running the Application:

- Launch the application by clicking the "Execute with Debugger" button.
- Log in as an author - [admin@example.com].
- Navigate to the "My Posts" page using the "My Posts" link in the navbar.
- Verify that the page displays all posts authored by the logged-in user.
- Confirm that the posts are ordered by creation date, with the most recent at the top (since this pages doesn't specify when the post was created, Navigate to the "Posts" page using the "Posts" link in the navbar to confirm the date the post was created).

 **Checklist**

- [x]  My code follows the style guidelines of this project.
- [x]  I have performed a self-review of my code.
- [x]  I have commented my code, particularly in hard-to-understand areas.
- [x]  My changes generate no new warnings or errors.
- [x]  I have added test instructions that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by sarahebrooks12 — CHANGES_REQUESTED** [review]
Please take the trello link out of the title and move it to the PR description 

List the posts as they should be displayed upon the user logging in with a specific email - admin@example.com - in the exact order that will be in the browser

This ticket does not state that edit delete publish or unpublish should be actionable items. That is a separate ticket.

**Comment by wicamo96** [comment]
I see my posts but each of the buttons are giving me a 404 error

**Comment by DeVanteFarmer** [comment]
Bugs/Issues resolved. Let me know if there's any further conflicts

**Comment by wicamo96** [comment]
Looks good!

**Review by sarahebrooks12 — APPROVED** [review]
👼🏻 Looks great!

**Comment by dmaceylewis** [comment]
Nice job!

**Pull request merged**
